- name: Install redis repos
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disabled_gng_check: true
- name: enable redis version
  ansible.builtin.shell: enable redis:remi-6.2 -y
- task: Install redis
  ansible.builtin.dnf:
    name: redis
    status: installed
- name: Replace listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis.conf
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: Replace listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis/redis.conf
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: start systemd service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes




